name: electrum_adapter
description: A client for Radiant ElectrumX servers
version: 2.0.4
homepage: https://github.com/moontreeapp/electrum_adapter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.9.0
  equatable: ^2.0.5
  json_rpc_2: ^3.0.2
  pedantic: ^1.11.1
  stream_channel: ^2.1.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  timing: ^1.0.0
#dependency_overrides:
#  json_stream_parser:
#    path: ../../repos/dart-json-stream-decoder
